### ISSUE TITLE
Only highlights the first result of a line

### ISSUE THREAD

**Issue by HoNamDuong** [nvim-pack/nvim-spectre#202]
![2024-01-06-150435_1316x703_scrot](https://github.com/nvim-pack/nvim-spectre/assets/91533350/eea767d6-b3f7-4f2e-8082-3286b6af6f42)

**Comment by EpsilonKu** [comment]
What do you mean?

**Comment by Nils-TUD** [comment]
I just ran into the same issue. The problem seems to be that highlighting is always done in lowercase and ignores the case-sensitive option of nvim-spectre:

Case sensitive:
![Screenshot_20240117_131128](https://github.com/nvim-pack/nvim-spectre/assets/2010758/217f7725-5f1e-461a-9d98-be8021ef2ae4)

Non case sensitive:
![Screenshot_20240117_131406](https://github.com/nvim-pack/nvim-spectre/assets/2010758/95705e90-0c62-452c-89ba-5555b41add0d)

**Comment by windwp** [comment]
switch to use oxi engine  for a better hightlight :). the highlight on sed is use vim regex.
