### ISSUE TITLE
Log "it is already running" after any replace and is nothing happing

### ISSUE THREAD

**Issue by adinvadim** [nvim-pack/nvim-spectre#232]
Mac OS, sed replace

gnu-sed and rg already installed

```
require('spectre').setup({ i})

vim.keymap.set('n', '<leader>S', '<cmd>lua require("spectre").toggle()<CR>', {
    desc = "Toggle Spectre"
})
vim.keymap.set('n', '<leader>sw', '<cmd>lua require("spectre").open_visual({select_word=true})<CR>', {
    desc = "Search current word"
})
vim.keymap.set('v', '<leader>sw', '<esc><cmd>lua require("spectre").open_visual()<CR>', {
    desc = "Search current word"
})
vim.keymap.set('n', '<leader>sp', '<cmd>lua require("spectre").open_file_search({select_word=true})<CR>', {
    desc = "Search on current file"
})
```

Default setup

After calling Spectre and trying to replace logging in bottom bar "it is already running"

**Comment by mayorbyrne** [comment]
Not sure it's relevant, since you mentioned having installed gnu-sed already, but I was having the exact same issue until I set up gnu-sed as the default `sed` -- if you type in `sed` in the terminal and it doesn't spit out the gnu-sed usage, it's not hitting the right one. As soon as I had it set up, the replace worked like a charm.

This comment explains it in a bit more detail:

https://gist.github.com/andre3k1/e3a1a7133fded5de5a9ee99c87c6fa0d?permalink_comment_id=4743045#gistcomment-4743045
