### ISSUE TITLE
Lookbehind and lookahead

### ISSUE THREAD

**Issue by danielespirito** [nvim-pack/nvim-spectre#38]
Can you post an example how to search with a lookbehind or lookahead? 
Search for a string with "(foo)@<=" is not giving me any results.

Thank you

**Comment by windwp** [comment]
it can't . 
ripgrep default has not supported it. 
even you can build a  custom ripgrep support look behind or lookahead but you can't use replace because `sed` regex doesn't support that syntax.
so better search for something more specify after that you can use `/` and use vim regex to filter it again with loobehind  syntax
then you can remove results by  press 'dd' :)
