### ISSUE TITLE
Options to cache last query

### ISSUE THREAD

**Issue by wongjiahau** [nvim-pack/nvim-spectre#66]
In VSCode, when I type a search query `foo` in the search panel, close it, and open it again, `foo`  will still be there.

However, whenever I open Spectre after closing it, my last query will always be cleared, which can be mildly annoying sometimes because I cannot remember my last query.

Therefore, is there anyway to cache the last query?

**Comment by denilson020898** [comment]
I did some research on nvim spectre source code. 
But not really caching it.
It will just search again the last keywords. 
But I would recommend to work with quick fix list rather than this.

spectre provides the following:
```
require('spectre.actions').get_current_entry()
require('spectre.actions').get_all_entries()
require('spectre.actions').get_state()
```

You can call `require('spectre.actions').get_state()` that returns the previous search keywords, which will return the following table
```
-- {
--   spectre_state = {
--     options = {
--       hidden = false,
--       ["ignore-case"] = true
--     },
--     query = {
--       is_file = "",
--       path = "",
--       replace_query = "",
--       search_quey = ""
--     }
--   }
-- }
```

You can reuse that to open a new search:

```
local M = {}
require('spectre').setup({
  is_insert_mode = false,
  live_update = true,
  mapping = {
    ['send_to_qf'] = {
      map = "<leader>q",
      cmd = "<cmd>lua require('spectre.actions').send_to_qf()<CR>",
      desc = "send all item to quickfix"
    },
  }
})

M.spectre_state = require('spectre.actions').get_state()
M.is_file = M.spectre_state.query.is_file
M.path = M.spectre_state.query.path
M.replace_query = M.spectre_state.query.replace_query
M.search_quey = M.spectre_state.query.search_quey

M.search_resume = function()
  M.spectre_state = require('spectre.actions').get_state()
  M.is_file = M.spectre_state.query.is_file
  M.path = M.spectre_state.query.path
  M.replace_query = M.spectre_state.query.replace_query
  M.search_query = M.spectre_state.query.search_query
  require('spectre').open({
    search_text = M.search_query,
    replace_text = M.replace_query,
    path = M.path,
  })
end

return M
```

If you want it to work after you close neovim, consider to save the state to a JSON file.

**Comment by hexh250786313** [comment]
@denilson020898 It works!
