### ISSUE TITLE
open_visual lags 1 step behind

### ISSUE THREAD

**Issue by konradmalik** [nvim-pack/nvim-spectre#79]
Hey, great plugin first of all!
I found a weird bug with open_visual function when applied in visual mode. Not sure if it's something with my setup.
It's supposed to search for a selected text, as far as I understand.
It does, but it lags 1 selection for some strange reason.
What I mean by that:
- select 'word1'
- run open_visual
- the search box is empty, looks like it does not work
- exit spectre. but then select 'word2' using visual mode
- run open_visual again
- now it searches fine, but for 'word1'
- if I now select 'word3' it'll search for 'word2' etc.

Is this just me? Or can you reproduce?

**Comment by windwp** [comment]
it should be `vnoremap <leader>s <esc>:lua require('spectre').open_visual()<CR>`

**Comment by quantumsnowball** [comment]
I am having the same issue, but only when setup the open_visual keymap in lua. It works as expected if I call it in vim command, or lua using vim.cmd 'vnoremap blahblah'.

I am using nvim-lazy as plugin manager, setting up the keymaps in side the `keys` table wrapped inside a function. The open_visual result is always delated by 1. I disabled lazy loading complete, and this problem still exists. 

Still not sure why this happen, but my temp fix is to call vim.cmd 'vnoremap blahblah' instead of fancy lua function.

**Comment by sxyazi** [comment]
Same issue there with lazy.nvim, solved by bind command string:

```lua
keys = {
  { "<leader>f", ":lua require('spectre').open()<CR>", mode = "n", silent = true },
  { "<leader>f", ":lua require('spectre').open_visual()<CR>", mode = "v", silent = true },
},
```
