### ISSUE TITLE
[Feature request] Toggle command

### ISSUE THREAD

**Issue by adelarsq** [nvim-pack/nvim-spectre#91]
Would be nice a toggle command, that allows to hide the Spectre window.

By the way, nice name! Spectre it's one of my favorites heroes 😄

**Comment by windwp** [comment]
Thanks i really like that name too. even i always play support and offlane.

**Comment by fjchen7** [comment]
Hi @windwp how to use command `resume_last_search()`? I use `open()` and search in spectre window, and use `:q` to exit. Then I use `open()` again and `resume_last_search()`, but nothing is resumed in spectre window.

**Comment by itsFrank** [comment]
This issue is marked as closed, but I was not able to figure out how to toggle the panel via the same keymap (which I believe is what the original issue was about).

I was able to get the desired behavior with this keymap function which relies on `spectre.state`:

```lua
vim.keymap.set("n", "<leader>sp", function()
    local spectre = require("spectre")
    local spectre_state = require("spectre.state")
    
    local is_open = false
    if spectre_state.bufnr ~= nil then
        local wins = vim.fn.win_findbuf(spectre_state.bufnr)
        if next(wins) ~= nil then -- check if wins is empty
            is_open = true
        end
    end

    if is_open then
        spectre.close()
    else
        spectre.open()
    end
end, { desc = "Toggle [S][P]ectre search" })
```
I have not yet figured out how to make it work with resume last search unfortunately. 

@windwp did I miss a command or function that could provide this toggle behavior without having to implement this function?

**Comment by itsFrank** [comment]
Circling back, anyone reading this, no need to use my code anymore, this does exactly the same thing:
```lua
require("spectre").toggle()
```
